#!/usr/bin/sh
HOSTNAME=bbld
ZONE=Europe/Oslo
USER=s
HOME=/home/$USER
CFG=$HOME/.config
SHELL=/user/bin/fish

# Locale
echo en_US.UTF-8 UTF-8\nde_DE.UTF-8 UTF-8\nfr_FR.UTF-8\nnb_NO.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf

# Time
ln -s /usr/share/zoneinfo/$ZONE /etc/localtime
hwclock --systohc --localtime

# Hostname
echo $HOSTNAME > /etc/hostname

mkinitcpio -p linux

passwd

pacman -Syu --noconfirm
pacman -S fish --noconfirm

# Make user and give administrator privileges to group wheel
useradd -g users -G wheel -m -s /usr/bin/fish
sed -i '/# %wheel ALL=(ALL) ALL/c\%wheel ALL=(ALL) ALL' /etc/sudoers

# Setup bootloader
pacman -S gptfdisk vim syslinux --noconfirm
syslinux-install_update -iam
sed -i 's|APPEND root=/dev/sda3 rw|APPEND root=/dev/sda2' /boot/syslinux/syslinux.cfg

# Yaourt
su s -c ./install-yaourt

# Install packages
su s -c ./install-packages

# Setup user
su s -c ./setup-user

systemctl enable $LOGINMGR
systemctl enable ntpd

reboot
